### PR TITLE
Changed firebases .on() to .once()

### PR DESCRIPTION
**Pull request by Lergin**
The .on() function creates a listener that is called every time the data is updated when the data in the firebase realtime database changes while .once() only gets the data one time. In the current version the .on() is used but in the way .once() should be used. (eg. the updateStatsics() function is called every 5 seconds and so creates a new listener every 5 seconds so that, if a data update happens, all the listeners are called what creates a lot of unwanted code executions)

Maybe it would be even better to still use .on() but only call the functions once so that the data is updated as soon as new data is available.

see: https://firebase.google.com/docs/database/web/read-and-write#read_data_once

### CODE REVIEW

**Comment by nikriek** [comment]
Thank you for you PR! We are actually aware of that. A fix should be this PR: https://github.com/Bestes-SPD-Hackathon-Team/Schulzzug-JS/pull/107

**Comment by nikriek** [comment]
Do you mind if I close this PR for now? Changes can be made to the one above ;)

**Comment by Lergin** [comment]
Ah i haven't looked into that one :)

**Comment by nikriek** [comment]
Yeah sorry, the title is that good ;)

**Comment by 5chdn** [comment]
@nikriek can you add them to #107 ?

**Comment by nikriek** [comment]
I did already..

**Comment by nikriek** [comment]
We are merging it as a hot fix. The other PR would break our clients.

**Pull request merged**
